-- One-off Snowflake setup for Tellio's vulnerability analysis. Run as ACCOUNTADMIN (or a role that can create these),
-- then put the names in backend/.env (SNOWFLAKE_*). Rename anything you like; keep .env in step.
-- The backend also runs the CREATE TABLE IF NOT EXISTS itself, so the table step is optional.

CREATE WAREHOUSE IF NOT EXISTS TELLIO_WH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS TELLIO;
CREATE SCHEMA IF NOT EXISTS TELLIO.PUBLIC;

CREATE ROLE IF NOT EXISTS TELLIO_APP;
GRANT USAGE ON WAREHOUSE TELLIO_WH TO ROLE TELLIO_APP;
GRANT USAGE ON DATABASE TELLIO TO ROLE TELLIO_APP;
GRANT USAGE, CREATE TABLE ON SCHEMA TELLIO.PUBLIC TO ROLE TELLIO_APP;
-- Only for SNOWFLAKE_CORTEX_MODEL:
-- GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE TELLIO_APP;

-- Pseudonymous per-trainee aggregates (one row per scam category or tactic). No uid, email, profile or message text.
CREATE TABLE IF NOT EXISTS TELLIO.PUBLIC.TELLIO_SKILL_STATS (
  TRAINEE STRING NOT NULL, DIMENSION STRING NOT NULL, AREA STRING NOT NULL,
  ATTEMPTS INTEGER NOT NULL, CORRECT INTEGER NOT NULL, FELL_FOR INTEGER NOT NULL,
  MESSAGE_ATTEMPTS INTEGER NOT NULL, REPORTED INTEGER NOT NULL, LINK_CLICKS INTEGER NOT NULL,
  AVG_RESPONSE_MS FLOAT, RECENT_ACCURACY FLOAT, EARLIER_ACCURACY FLOAT,
  UPDATED_AT TIMESTAMP_LTZ NOT NULL DEFAULT CURRENT_TIMESTAMP());
GRANT SELECT, INSERT, UPDATE ON TABLE TELLIO.PUBLIC.TELLIO_SKILL_STATS TO ROLE TELLIO_APP;

-- A service user for the backend, then a programmatic access token for it (the secret goes in SNOWFLAKE_PAT).
CREATE USER IF NOT EXISTS TELLIO_SVC TYPE = SERVICE DEFAULT_ROLE = TELLIO_APP DEFAULT_WAREHOUSE = TELLIO_WH;
GRANT ROLE TELLIO_APP TO USER TELLIO_SVC;
-- PATs need a network policy on the user by default. Either attach one that allows the backend's egress IPs:
--   CREATE NETWORK POLICY TELLIO_NET ALLOWED_IP_LIST = ('203.0.113.10');
--   ALTER USER TELLIO_SVC SET NETWORK_POLICY = TELLIO_NET;
-- or, for a hackathon demo only, relax that requirement for this user:
--   CREATE AUTHENTICATION POLICY TELLIO_PAT_POLICY PAT_POLICY = (NETWORK_POLICY_EVALUATION = ENFORCED_NOT_REQUIRED);
--   ALTER USER TELLIO_SVC SET AUTHENTICATION POLICY TELLIO_PAT_POLICY;
ALTER USER TELLIO_SVC ADD PROGRAMMATIC ACCESS TOKEN TELLIO_BACKEND ROLE_RESTRICTION = 'TELLIO_APP' DAYS_TO_EXPIRY = 30;
