// Email practice scenarios. Every company and web address here is invented.
import type { EmailScenario } from './scenarios.ts'

export const emailScenarios: EmailScenario[] = [
  {
    id: 'bank-sign-in',
    type: 'email',
    tactics: ['fear', 'urgency', 'info_request', 'suspicious_link'],
    title: 'Unusual sign-in alert',
    summary: 'Your bank says someone tried to sign in to your account.',
    situation: 'You bank with Maplewood Bank and use its app most weeks.',
    difficulty: 'easy',
    correctAction: 'report',
    fromName: 'Maplewood Bank',
    fromAddress: 'security@maplewood-bank-alerts.com',
    subject: 'Action required: unusual sign-in to your account',
    receivedAt: '6:41 AM',
    body: [
      'Dear Customer,',
      'We detected a sign-in to your online banking from a new device in Toronto, ON. If this was not you, your account will be locked within 12 hours to protect your funds.',
      'To keep access, confirm your identity now using the secure link below. You will need your card number and online banking password.',
      'Maplewood Bank Security Team',
    ],
    links: ['https://maplewoodbank.account-verify.net/secure'],
    indicators: [
      { quote: 'maplewood-bank-alerts.com', title: "An address that isn't the bank's", detail: 'The name says Maplewood Bank, but tap it and the address ends in maplewood-bank-alerts.com. Anyone can register a name like that. Your bank sends email from its own web address.' },
      { quote: 'Dear Customer,', title: "It doesn't know your name", detail: 'Your bank knows who you are. A greeting that could go to anyone suggests the same email went to thousands of people.' },
      { quote: 'your account will be locked within 12 hours', title: 'A threat with a deadline', detail: 'Fear and a countdown are there to make you act before you stop and check.' },
      { quote: 'your card number and online banking password', title: 'It asks for your password', detail: 'Your bank will never ask you to type your password into a page you reached from an email.' },
      { quote: 'https://maplewoodbank.account-verify.net/secure', title: 'A look-alike web address', detail: 'Read the address up to the first single slash. The site you would actually visit is account-verify.net. "maplewoodbank" is only a label in front of it.' },
    ],
    explanation: 'This is a phishing email. It copies your bank\'s name, threatens to lock your account, and sends you to a look-alike page to collect your password and card number.',
    nextTime: "When an email says something is wrong with your account, don't use its link. Open your bank's app or type its web address yourself and check there.",
  },
  {
    id: 'book-order',
    type: 'email',
    tactics: [],
    title: 'Order confirmation',
    summary: 'A bookshop confirms the order you placed yesterday.',
    situation: 'Yesterday you ordered two books from Fernleaf Books, a shop whose website is fernleafbooks.ca.',
    difficulty: 'medium',
    correctAction: 'safe',
    fromName: 'Fernleaf Books',
    fromAddress: 'orders@fernleafbooks.ca',
    subject: 'Your Fernleaf Books order #48213',
    receivedAt: '10:15 AM',
    body: [
      'Hi Sam,',
      'Thanks for your order. Here is what you bought: The Quiet Garden and A Short History of Tea, $41.98 including tax, paid with the card ending in 4417.',
      "We'll email you again when it ships. You can check your order at any time from your account on our website.",
      'Happy reading,',
      'The Fernleaf Books team',
    ],
    links: ['https://fernleafbooks.ca/account/orders/48213'],
    indicators: [
      { quote: 'The Quiet Garden and A Short History of Tea', title: 'It matches what you did', detail: 'These are the books you ordered, for a price you recognize. An email about something you were expecting is a good sign.' },
      { quote: 'orders@fernleafbooks.ca', title: "The address is the shop's own", detail: 'Tap the sender name and the address ends in fernleafbooks.ca, the same as the shop\'s website.' },
      { quote: 'https://fernleafbooks.ca/account/orders/48213', title: 'The link goes to the real site', detail: 'Read the address up to the first single slash: fernleafbooks.ca. That is the shop you ordered from, not a look-alike.' },
      { quote: "We'll email you again when it ships.", title: 'No pressure, nothing to hand over', detail: "It doesn't ask for a password, a payment or a deadline. It only tells you what happens next." },
    ],
    explanation: 'Real receipts tend to look like this: you were expecting it, the details match, the sender and link point to the shop\'s own website, and it asks for nothing.',
    nextTime: 'Being careful is never wrong. To tell real emails apart, tap the sender name and check the address, check where links really go, and ask whether you were expecting it.',
  },
  {
    id: 'tax-refund',
    type: 'email',
    tactics: ['authority', 'reward', 'urgency', 'info_request'],
    title: 'Tax refund waiting',
    summary: 'The tax agency says you have a refund to claim online.',
    situation: 'You filed your taxes in April and got your notice of assessment in May.',
    difficulty: 'medium',
    correctAction: 'report',
    fromName: 'Canada Revenue Agency',
    fromAddress: 'notice@cra-refund-centre.info',
    subject: 'You have a pending tax refund of $612.40',
    receivedAt: '3:27 PM',
    body: [
      'Hello,',
      'After a review of your return, you are eligible for an additional refund of $612.40. To receive it by Interac e-Transfer, complete the deposit form with your Social Insurance Number and banking details.',
      'Unclaimed refunds expire after 72 hours.',
      'Canada Revenue Agency',
    ],
    links: ['https://cra-refund.ca-deposit.info/claim'],
    indicators: [
      { quote: 'notice@cra-refund-centre.info', title: "Not a government address", detail: 'Tap the name and the address ends in cra-refund-centre.info. Government of Canada email and websites use canada.ca or gc.ca.' },
      { quote: 'you are eligible for an additional refund', title: "Money you weren't expecting", detail: 'Your taxes were already settled. A surprise refund is tempting, which is exactly why scammers use it.' },
      { quote: 'your Social Insurance Number and banking details', title: 'It asks for your SIN and bank details', detail: 'The CRA says it will not email you a link asking for personal or financial information. Your SIN is worth protecting.' },
      { quote: 'Unclaimed refunds expire after 72 hours.', title: 'A deadline to rush you', detail: 'A real refund does not vanish because you waited a few days to check.' },
      { quote: 'https://cra-refund.ca-deposit.info/claim', title: 'A look-alike web address', detail: 'Read the address up to the first single slash. The site you would actually visit is ca-deposit.info. "cra-refund" is only a label in front of it.' },
    ],
    explanation: 'This is a tax refund scam. It uses the agency\'s name and a surprise refund to collect your Social Insurance Number and banking details.',
    nextTime: 'If an email mentions a refund or money owed, sign in to your tax account yourself, by typing the address, and check there.',
  },
  {
    id: 'contractor-invoice',
    type: 'email',
    tactics: ['authority'],
    title: 'Updated invoice from your contractor',
    summary: "Your contractor's final invoice arrives with new bank details.",
    situation: 'Cedar & Sons Contracting is finishing your new deck. You expect their final invoice this week.',
    difficulty: 'hard',
    correctAction: 'report',
    fromName: 'Cedar & Sons Contracting',
    fromAddress: 'billing@cedarandsons.ca',
    replyTo: 'cedarandsons.billing@fastmail-box.net',
    subject: 'Final invoice for your deck, #1042',
    receivedAt: '11:52 AM',
    body: [
      'Hi Sam,',
      "Thanks again for choosing us, we're glad the deck is nearly done. Your final invoice for $6,850.00 is attached.",
      'Please note our bank details have changed. Use the new account in the attached invoice for this payment, not the one on your quote.',
      "Our office phone is down this week, so just reply to this email if you have any questions.",
      'Dave, Cedar & Sons Contracting',
    ],
    attachment: 'Invoice_1042_updated.pdf',
    indicators: [
      { quote: 'our bank details have changed', title: 'New bank details by email', detail: 'A sudden change to where you send a large payment is the heart of this scam. The real business is unlikely to change accounts in the middle of a job.' },
      { quote: 'cedarandsons.billing@fastmail-box.net', title: 'Replies go somewhere else', detail: 'Tap the sender name: the email shows the right address, but replies go to a different one at fastmail-box.net. Someone wants your answers to skip the real business.' },
      { quote: 'Our office phone is down this week', title: 'A reason not to call', detail: 'Steering you away from the phone stops you checking with the people you actually know.' },
      { quote: 'Invoice_1042_updated.pdf', title: "Details you can't check in the email", detail: 'The new account number sits inside an attachment. Nothing in it proves who wrote it. Opening unexpected files can also be risky.' },
    ],
    explanation: 'This is an invoice scam. Scammers sometimes get into a real business\'s email, so the sender looks right and the timing fits. The giveaway is the changed bank details, the hidden reply-to and the excuse not to call.',
    nextTime: 'Before paying a changed account, call the business on a number you already have, like the one on your quote, and ask them to confirm.',
  },
]
